### ISSUE TITLE
Low Cardinality support?

### ISSUE THREAD

**Issue by asad-awadia** [Ecwid/clickhouse-client#15]
I am trying to do a basic select * from table

where one of the columns is of type 'LowCardinality(String)'

and the client errors out with Unknown ClickHouse type 'LowCardinality(String)'

Is LowCardinality(String) not supported? how do i read this value?

**Comment by vgv** [comment]
Hi @asad-awadia, the fix was released a few hours ago.
Please, update your lib to the version `0.13.0`
