### ISSUE TITLE
Usage of Kotlin internal declaration from different module

### ISSUE THREAD

**Issue by amy108** [Ecwid/clickhouse-client#3]
![image](https://user-images.githubusercontent.com/48902828/82007509-fe13da80-969c-11ea-8593-8a85e8301e3a.png)
hello,how to solve the problem in java project?

**Comment by vgv** [comment]
Hi

Why do you need `MappedResponse`?
I think you should use interface `ClickHouseResponse<T>` instead of concrete implementation.
